домашнє завдання №1

In [2]:
import numpy as np

In [13]:

x = np.arange(1, 11)
print('result:')
print(x)

result:
[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
data = np.zeros((3, 3), dtype=int)
print('result:')
print(data)

result:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
random_matrix = np.random.randint(1, 11, size=(5, 5))

print("Матриця з випадковими цілими числами:")
print(random_matrix)

Матриця з випадковими цілими числами:
[[ 3  1  2  5  3]
 [ 4  1  1  4  3]
 [ 2  5  1  8  7]
 [ 7  8  5  4  8]
 [10  8  9  7  3]]


In [ ]:
random_matrix = np.random.rand(4, 4)

print("Матриця з випадковими дійсними числами:")
print(random_matrix)

Матриця з випадковими дійсними числами:
[[0.39636384 0.7407556  0.45500489 0.00854627]
 [0.17583935 0.05154755 0.14639151 0.25577892]
 [0.24123619 0.34173635 0.35363293 0.8891729 ]
 [0.33025845 0.43687793 0.29342451 0.25889972]]


In [ ]:
np.round(np.random.rand(4, 4), 3)

array([[0.367, 0.235, 0.563, 0.786],
       [0.308, 0.863, 0.463, 0.685],
       [0.121, 0.562, 0.061, 0.382],
       [0.08 , 0.236, 0.868, 0.313]])

In [12]:
x = np.random.randint(1, 11, size=(5))
print(x)
y = np.random.randint(1, 11, size=(5))
print(y)
print('result:')
print(x+y)
print(x-y)
print(x*y)

[1 5 5 9 9]
[ 1 10 10 10  5]
result:
[ 2 15 15 19 14]
[ 0 -5 -5 -1  4]
[ 1 50 50 90 45]


In [7]:
a = np.random.randn(7)
b = np.random.randn(7)
print(a)
print(b)
print('result:')
c = np.dot(a, b)
print(c)


[ 2.94842027 -0.81484082 -0.73456235 -0.04303329  0.33051002  0.92551589
 -0.43558731]
[-0.5719434   2.41222059 -1.06593594  0.37965255  1.28777851 -0.22905624
  0.05886869]
result
-2.6972605470789683


In [8]:
x = np.random.randint(1, 11, size=(2, 2))
print(x)
y = np.random.randint(1, 11, size=(2, 3))
print(y)
print('result:')
c = np.dot(x, y)
print(c)

[[5 1]
 [8 1]]
[[6 2 9]
 [4 3 3]]
result
[[34 13 48]
 [52 19 75]]


In [9]:
x = np.random.randint(1, 11, size=(3, 3))
print(x)
print('result:')
x_inv = np.linalg.inv(x)
print(x_inv)

[[9 7 6]
 [8 9 1]
 [4 5 1]]
result
[[ 0.125    0.71875 -1.46875]
 [-0.125   -0.46875  1.21875]
 [ 0.125   -0.53125  0.78125]]


In [10]:
random_matrix = np.random.rand(3,3)
print(random_matrix)
print('result:')
print(random_matrix.T)

[[0.77688335 0.29400352 0.44214267]
 [0.56336085 0.94891371 0.30466541]
 [0.94365776 0.61506773 0.00560988]]
result
[[0.77688335 0.56336085 0.94365776]
 [0.29400352 0.94891371 0.61506773]
 [0.44214267 0.30466541 0.00560988]]


In [11]:
x = np.random.randint(1, 11, size=(3, 4))
y = np.random.randint(1, 11, size=(4, ))
print(x)
print(y)
print('result:')
c = np.dot(x, y)
print(c)

[[1 4 4 6]
 [9 7 4 2]
 [7 7 7 8]]
[1 6 5 5]
result
[ 75  81 124]


In [17]:
x = np.random.rand(2,3)
y = np.random.rand(3,)
print(x)
print(y)
print('result:')
c = np.dot(x, y)
print(c)

[[0.40674074 0.70032771 0.80176213]
 [0.19419165 0.77747428 0.2844672 ]]
[0.69301683 0.28100016 0.15068391]
result:
[0.59948303 0.39591311]


In [18]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(x)
print(y)
print('result:')
c = x*y
print(c)

[[9 3]
 [3 4]]
[[7 7]
 [3 3]]
result:
[[63 21]
 [ 9 12]]


In [19]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(x)
print(y)
print('result:')
c = np.dot(x, y)
print(c)

[[3 1]
 [9 5]]
[[ 2 10]
 [ 1  8]]
result:
[[  7  38]
 [ 23 130]]


In [20]:
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print('result:')
print(a.sum())

[[12 22 40 65  3]
 [40 61 99 85 43]
 [41 40 38  1 57]
 [86 16 25 81 99]
 [25 88 46 85 75]]
result:
1273


In [21]:
x = np.random.randint(1, 11, size=(4, 4))
y = np.random.randint(1, 11, size=(4, 4))
print(x)
print(y)
print('result:')
z = x - y
print(z)

[[ 5  8  5  5]
 [ 9 10  9  4]
 [ 8  5  2  3]
 [ 7  1  3 10]]
[[ 4  7  5  2]
 [ 1  7 10  6]
 [ 5 10  7  3]
 [ 7 10 10  7]]
result:
[[ 1  1  0  3]
 [ 8  3 -1 -2]
 [ 3 -5 -5  0]
 [ 0 -9 -7  3]]


In [3]:
a = np.random.rand(3,3)
print(a)
v = np.array([a[0, ].sum(), a[1, ].sum(), a[2, ].sum()])
print('result')
print(v)

[[0.08217667 0.02744288 0.29378703]
 [0.48072965 0.57736157 0.82892279]
 [0.33777231 0.02248793 0.6252229 ]]
result
[0.40340658 1.88701402 0.98548313]


In [28]:
a = np.random.randint( 1, 1111, size=(3, 4))
print(a)
z = np.square(a)
print(z)

[[ 644  414 1034  439]
 [ 329  299  286   84]
 [ 805 1050  224  631]]
[[ 414736  171396 1069156  192721]
 [ 108241   89401   81796    7056]
 [ 648025 1102500   50176  398161]]


In [32]:
v = np.random.randint( 1, 51, size=(4))
print(v)
a = np.sqrt(v)
print('result')
print(a)

[ 5 23 14 25]
result
[2.23606798 4.79583152 3.74165739 5.        ]
